server:
  port: 8887
mysql:
  host: localhost
  port: 49802
  username: root
  password: root
  dbname: shopdevgo
  maxIdlesConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600

logger:
  log_level: "debug"
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true


redis:
  host: localhost
  port: 6379
  password:
  database: 0
  pool_size: 10